<?php require 'templates/layout/header.phtml' ?>
<div class="d-flex flex-column min-vh-100">
    <main class="flex-grow-1">
        <h1>Hola, <span class="navbar-text me-3"><?= htmlspecialchars($_SESSION['usuario']); ?></span></h1>
        <h2>Contenido del panel de administración</h2>
         <a class="btn btn-custom" href="<?= BASE_URL ?>pilotoNuevo">Nuevo Piloto</a>
         <a class="btn btn-custom" href="<?= BASE_URL ?>editarPilotos">Editar Pilotos</a>
         <a class="btn btn-custom" href="<?= BASE_URL ?>carreraNueva">Nueva Carrera</a>
    </main>
    <?php require 'templates/layout/footer.phtml' ?>
</div>