<?php require 'templates/layout/header.phtml' ?>

<div class="d-flex flex-column min-vh-100">

    <div class="position-relative flex-grow-1 overflow-hidden d-flex justify-content-center align-items-center">
        <h1 class="position-absolute text-white text-center display-3 z-1">
            POLEPOSITION
        </h1>

        <img src="<?= BASE_URL ?>assets/kartingBg2.jpg" alt="Imagen Destacada"
            class="w-100 h-100 object-fit-cover position-absolute top-0 start-0">
    </div>
    <?php require 'templates/layout/footer.phtml' ?>
</div>