<?php require 'templates/layout/header.phtml' ?>

<?php if ($error): ?>
<div class="alert alert-danger py-3 mt-5 position-absolute w-100" role='alert'>
    <?= $error ?>
</div>
<?php endif ?>

<div class="d-flex flex-column min-vh-100">

    <main class="flex-grow-1 d-flex justify-content-center align-items-center">
        <div class="row border rounded-5 p-3 shadow box-area w-75">
            
            <!-- Columna izquierda con imagen -->
            <div class="col-md-6 rounded-4 d-flex justify-content-center align-items-center flex-column left-box overflow-hidden p-0">
                <img src="<?= BASE_URL ?>assets/kartingBg.jpg" 
                     alt="Imagen Destacada" 
                     class="img-fluid w-100 h-100 object-fit-cover">
            </div>

            <!-- Columna derecha con formulario -->
            <div class="col-md-6 d-flex flex-column justify-content-center align-items-center right-box p-5">
                <h2 class="mb-2">PolePosition</h2>
                <p>Gestión ágil, rendimiento al máximo.</p>
                <form method='POST' action='login' class="w-100 mt-4">
                    <div class='form-floating mt-3'>
                        <input type="text" class="form-control" id="usuario" name='username' placeholder="Usuario" required>
                        <label for="floatingInput">Usuario</label>
                    </div>
                    <div class='form-floating mt-3'>
                        <input type='password' class='form-control' id='contraseña' name='pass' placeholder="Contraseña" required>
                        <label for='floatingInput'>Contraseña</label>
                    </div>
                    <div class="d-flex justify-content-center">
                        <button type='submit' class='btn btn-custom mt-4 px-5'>Login</button>
                    </div>
                </form>
            </div>

            
        </div>
    </main>
    <!-- Footer (se mantiene abajo incluso si hay poco contenido) -->
    <?php require 'templates/layout/footer.phtml' ?>
</div>