<?php require 'templates/layout/header.phtml' ?>

<div class="d-flex flex-column min-vh-100">
    <main class="flex-grow-1">

        <div class="container py-5 mt-5">
            <div class="row">
                <h1 class="mb-4">Pilotos</h1>
                <form method="GET" action="<?= BASE_URL ?>pilotos" class="mb-3 d-flex">
                    <input type="text" name="q" class="form-control me-2" placeholder="Buscar piloto por nombre o apellido"
                        value="<?= isset($_GET['q']) ? htmlspecialchars($_GET['q']) : '' ?>">
                    <button type="submit" class="btn btn-custom">Buscar</button>
                </form>
                <?php foreach ($pilotos as $p): ?>
                    <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
                        <div class="card h-100 shadow">
                            <?php if (!empty($p->foto) && file_exists("assets/pilotos/" . $p->foto)): ?>
                                <img src="<?= BASE_URL ?>assets/pilotos/<?= htmlspecialchars($p->foto) ?>" class="card-img-top" alt="<?= htmlspecialchars($p->nombre) ?>">
                            <?php else: ?>
                                <img src="<?= BASE_URL ?>assets/pilotos/pilotoDefault.jpg" class="card-img-top" alt="Piloto sin foto">
                            <?php endif; ?>
                            <div class="card-body text-center d-flex flex-column">
                                <h5 class="card-title"><?= htmlspecialchars($p->nombre) . " " . htmlspecialchars($p->apellido) ?></h5>
                                <a class="btn btn-custom " href="<?= BASE_URL ?>piloto/<?= $p->piloto_id ?>">Mas Info</a>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </main>

    <?php require 'templates/layout/footer.phtml' ?>
</div>