<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Quicksand:wght@300..700&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="<?= BASE_URL ?>css/style.css">
    <title>PolePosition</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg custom-navbar position-fixed top-0 z-1 w-100">
            <div class="container-fluid">
                <a class="navbar-brand" href="<?= BASE_URL ?>">PolePosition</a>
                <div class="d-flex align-items-center">

                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="<?= BASE_URL ?>">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= BASE_URL ?>carreras">Carreras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= BASE_URL ?>pilotos">Pilotos</a>
                        </li>
                        <?php if (isset($_SESSION['usuario'])): ?>
                            <li class="nav-item">

                            </li>
                        <?php endif; ?>
                        <?php if (isset($_SESSION['usuario'])): ?>
                            <a class="nav-link" href="<?= BASE_URL ?>admin">Panel Admin</a>
                            <!-- <span class="navbar-text me-3"><?= htmlspecialchars($_SESSION['usuario']); ?></span> -->
                            <form method="post" action="authController.php?action=logout" class="d-inline">
                                <button type="submit" class="btn btn-danger">Cerrar sesión</button>
                            </form>
                        <?php else: ?>
                            <a href="<?= BASE_URL ?>login" class="btn btn-custom">Login</a>
                        <?php endif; ?>
                </div>
        </nav>
    </header>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>